### ISSUE TITLE
Wake up from deep sleep on battery

### ISSUE THREAD

**Issue by KitWallace** [KitWallace/TreeCare#2]
Ive now plugged in the 18650 batteries and whilst it runs fine, it doesn't wake from deep sleep on battery - It did used to a fresh LiPo.  There seems to be some stuff on the ESP32 forum - maybe its the power pulse on wake-up?

https://www.esp32.com/viewtopic.php?t=19335&p=72346

Need to understand deep sleep better.

**Comment by KitWallace** [comment]
I should add that this is a problem on the Wifi version  - more of a problem if it occurs on the GSM version

**Comment by KitWallace** [comment]
same problem with the same code on the V1.4 board -  needs a hard reset and voltage reported is 3.9  - sane thing if I just use delay - very puzzling

**Comment by KitWallace** [comment]
Power management code needed for all on-battery usage  -  treat as solved

**Comment by IanMitchell77** [comment]
@KitWallace ,
What was the power management code that fixed this?
I thought that using the 18650 batteries solved this?
